/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShopImport } from './routes/shop'
import { Route as InstallationsResidentialImport } from './routes/installations-residential'
import { Route as InstallationsHospitalityImport } from './routes/installations-hospitality'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ShopRoute = ShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRoute,
} as any)

const InstallationsResidentialRoute = InstallationsResidentialImport.update({
  id: '/installations-residential',
  path: '/installations-residential',
  getParentRoute: () => rootRoute,
} as any)

const InstallationsHospitalityRoute = InstallationsHospitalityImport.update({
  id: '/installations-hospitality',
  path: '/installations-hospitality',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/installations-hospitality': {
      id: '/installations-hospitality'
      path: '/installations-hospitality'
      fullPath: '/installations-hospitality'
      preLoaderRoute: typeof InstallationsHospitalityImport
      parentRoute: typeof rootRoute
    }
    '/installations-residential': {
      id: '/installations-residential'
      path: '/installations-residential'
      fullPath: '/installations-residential'
      preLoaderRoute: typeof InstallationsResidentialImport
      parentRoute: typeof rootRoute
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/installations-hospitality': typeof InstallationsHospitalityRoute
  '/installations-residential': typeof InstallationsResidentialRoute
  '/shop': typeof ShopRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/installations-hospitality': typeof InstallationsHospitalityRoute
  '/installations-residential': typeof InstallationsResidentialRoute
  '/shop': typeof ShopRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/installations-hospitality': typeof InstallationsHospitalityRoute
  '/installations-residential': typeof InstallationsResidentialRoute
  '/shop': typeof ShopRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/installations-hospitality'
    | '/installations-residential'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/installations-hospitality'
    | '/installations-residential'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/installations-hospitality'
    | '/installations-residential'
    | '/shop'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InstallationsHospitalityRoute: typeof InstallationsHospitalityRoute
  InstallationsResidentialRoute: typeof InstallationsResidentialRoute
  ShopRoute: typeof ShopRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InstallationsHospitalityRoute: InstallationsHospitalityRoute,
  InstallationsResidentialRoute: InstallationsResidentialRoute,
  ShopRoute: ShopRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/installations-hospitality",
        "/installations-residential",
        "/shop"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/installations-hospitality": {
      "filePath": "installations-hospitality.tsx"
    },
    "/installations-residential": {
      "filePath": "installations-residential.tsx"
    },
    "/shop": {
      "filePath": "shop.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
