/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShopImport } from './routes/shop'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as ProfileImport } from './routes/profile'
import { Route as InstallationsResidentialImport } from './routes/installations-residential'
import { Route as InstallationsHospitalityImport } from './routes/installations-hospitality'
import { Route as AboutImport } from './routes/about'
import { Route as SplatImport } from './routes/$'
import { Route as IndexImport } from './routes/index'
import { Route as ViewInstallationIdImport } from './routes/view-installation/$id'
import { Route as AdminDashboardImport } from './routes/admin/dashboard'

// Create/Update Routes

const ShopRoute = ShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const InstallationsResidentialRoute = InstallationsResidentialImport.update({
  id: '/installations-residential',
  path: '/installations-residential',
  getParentRoute: () => rootRoute,
} as any)

const InstallationsHospitalityRoute = InstallationsHospitalityImport.update({
  id: '/installations-hospitality',
  path: '/installations-hospitality',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ViewInstallationIdRoute = ViewInstallationIdImport.update({
  id: '/view-installation/$id',
  path: '/view-installation/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/installations-hospitality': {
      id: '/installations-hospitality'
      path: '/installations-hospitality'
      fullPath: '/installations-hospitality'
      preLoaderRoute: typeof InstallationsHospitalityImport
      parentRoute: typeof rootRoute
    }
    '/installations-residential': {
      id: '/installations-residential'
      path: '/installations-residential'
      fullPath: '/installations-residential'
      preLoaderRoute: typeof InstallationsResidentialImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof rootRoute
    }
    '/view-installation/$id': {
      id: '/view-installation/$id'
      path: '/view-installation/$id'
      fullPath: '/view-installation/$id'
      preLoaderRoute: typeof ViewInstallationIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/installations-hospitality': typeof InstallationsHospitalityRoute
  '/installations-residential': typeof InstallationsResidentialRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/view-installation/$id': typeof ViewInstallationIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/installations-hospitality': typeof InstallationsHospitalityRoute
  '/installations-residential': typeof InstallationsResidentialRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/view-installation/$id': typeof ViewInstallationIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/installations-hospitality': typeof InstallationsHospitalityRoute
  '/installations-residential': typeof InstallationsResidentialRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/view-installation/$id': typeof ViewInstallationIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/installations-hospitality'
    | '/installations-residential'
    | '/profile'
    | '/reset-password'
    | '/shop'
    | '/admin/dashboard'
    | '/view-installation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/installations-hospitality'
    | '/installations-residential'
    | '/profile'
    | '/reset-password'
    | '/shop'
    | '/admin/dashboard'
    | '/view-installation/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/installations-hospitality'
    | '/installations-residential'
    | '/profile'
    | '/reset-password'
    | '/shop'
    | '/admin/dashboard'
    | '/view-installation/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  InstallationsHospitalityRoute: typeof InstallationsHospitalityRoute
  InstallationsResidentialRoute: typeof InstallationsResidentialRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ViewInstallationIdRoute: typeof ViewInstallationIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  InstallationsHospitalityRoute: InstallationsHospitalityRoute,
  InstallationsResidentialRoute: InstallationsResidentialRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ViewInstallationIdRoute: ViewInstallationIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$",
        "/about",
        "/installations-hospitality",
        "/installations-residential",
        "/profile",
        "/reset-password",
        "/shop",
        "/admin/dashboard",
        "/view-installation/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/installations-hospitality": {
      "filePath": "installations-hospitality.tsx"
    },
    "/installations-residential": {
      "filePath": "installations-residential.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/shop": {
      "filePath": "shop.tsx"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.tsx"
    },
    "/view-installation/$id": {
      "filePath": "view-installation/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
